
-- SHIL SOLAR Supabase schema
-- Run this file in Supabase SQL Editor.

create extension if not exists "pgcrypto";

do $$ begin
  create type user_status as enum ('pending', 'approved', 'rejected', 'blocked');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type user_role as enum ('user', 'expert', 'admin');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  phone text,
  company text,
  role user_role not null default 'user',
  status user_status not null default 'pending',
  request_note text,
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'SHIL SOLAR Project',
  client_name text,
  city text,
  system_type text,
  status text default 'draft',
  project_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  route text,
  metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  );
$$;

create or replace function public.is_approved()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and status = 'approved'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, phone, company, request_note, status, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'company', ''),
    coalesce(new.raw_user_meta_data ->> 'request_note', ''),
    'pending',
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.app_projects enable row level security;
alter table public.usage_events enable row level security;

drop policy if exists "profiles_read_self_or_admin" on public.profiles;
create policy "profiles_read_self_or_admin"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_self_limited" on public.profiles;
create policy "profiles_update_self_limited"
on public.profiles for update
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "projects_read_own_or_admin" on public.app_projects;
create policy "projects_read_own_or_admin"
on public.app_projects for select
using ((owner_id = auth.uid() and public.is_approved()) or public.is_admin());

drop policy if exists "projects_write_own_approved" on public.app_projects;
create policy "projects_write_own_approved"
on public.app_projects for insert
with check (owner_id = auth.uid() and public.is_approved());

drop policy if exists "projects_update_own_approved" on public.app_projects;
create policy "projects_update_own_approved"
on public.app_projects for update
using ((owner_id = auth.uid() and public.is_approved()) or public.is_admin())
with check ((owner_id = auth.uid() and public.is_approved()) or public.is_admin());

drop policy if exists "projects_delete_own_or_admin" on public.app_projects;
create policy "projects_delete_own_or_admin"
on public.app_projects for delete
using ((owner_id = auth.uid() and public.is_approved()) or public.is_admin());

drop policy if exists "events_insert_authenticated" on public.usage_events;
create policy "events_insert_authenticated"
on public.usage_events for insert
with check (auth.uid() = user_id or user_id is null);

drop policy if exists "events_admin_read" on public.usage_events;
create policy "events_admin_read"
on public.usage_events for select
using (public.is_admin());

-- IMPORTANT:
-- After your admin user signs up, run this once with your actual email:
-- update public.profiles set role='admin', status='approved', approved_at=now()
-- where email='YOUR_ADMIN_EMAIL@example.com';
